# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f90da7238b88a3183e4245b7848338616e063123b121cfd90459243df920a652cf043c44810b9f247fef16157d579a672168a62ffc8dc753a4137d2ec7d584c9

test:
  secret_key_base: e5475da87cd24624b26243547f12e024f67a7d9c254ca687fc93698ec0ff8a460d4bc716e84d43a63b4b03c50594d41e7bde3335c754536f307149a44c795772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
