# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = User.create! :first_name => 'Cosmin', :email => 'cosminstudio@gmail.com', :password => 'mihalache1988', :password_confirmation => 'mihalache1988', :role => 'admin'
 
# p "Created #{User.count} users"

Location.create!([
#  {name: "18 Lounge", description: "18Lounge is located on the rooftop of the City Gate South Tower, having large glass panels all around for a stunning overlooking of the city skyline, Herastrau Lake and Kiseleff Boulevard. Whether you would like to dine or have a drink, to entertain a group of clients or to host a large reception throughout the entire place, our home is your venue; 18Lounge seats up to 156 guests inside and up to 100 on the terrace. For standing receptions, the inside can accommodate up to 250 guests, a 15 meters long bar serving for a relaxed and at ease atmosphere.", slug: "18-lounge", picture: "Book-a-table-at-18-lounge.jpg", user_id: 2},
#  {name: "Bellini", description: "Bellini - The best Italian restaurant in 2010 Three years in a row, Bellini Restaurant, Italian, located in the University, Bucharest, was nominated by the magazine Time-Out in the category \"Best Italian restaurant,\" earning a place on the podium. Present on the market for nearly eight years, I have sought over time to improve our relationship with our customers and operate under the name \"Our customer, our master\". The restaurant staff is highly trained and kitchen staff is ready to sunny lands of Italy. Also, ingredients used in our dishes are brought from Italy by importing directly. We offer, besides comfort and exceptional service, some of the best recipes available in Bucharest. We thank our customers, without whom we would not have come this far and announce that we still open customer loyalty program, offering a discount card for the most loyal of them. More than 50 varieties of wines are carefully selected for you and are able to offer the best local wines and the best Italian. In 2009 Bellini Restaurant-University has signed a distribution agreement with vineyard \"Fontana -Fredda\" in Italy. We managed to bring in Romania the best wines from this vineyard. Thank you again and you're welcome and delicious cuisine in an Italian restaurant.", slug: "bellini", picture: "Book-a-table-at-bellini.jpg", user_id: 2},
#  {name: "Divan", description: "For those seeking an oriental culinary experiences, welcome to the Divan, bazaar for the senses! Here, the food is never just food! Turkish cuisine has ancient roots, Ottoman and Oriental accents that will conquer. Because Divan is where people gather to meet, to tell, to share their experiences and their plate, food different from yours. It is a magical place in the heart of Bucharest, the actual spirit dwells alike, noisy and bustling modern Turkey and traditional blast, full of stories and wisdom of the Turks of yore. Because Divan is the result of progress that respects and preserves the sanctity roots. So our dear mesean, urge you to enjoy traditional Turkish dishes, and dancing nightly to watch the show inviting the Ottoman our princesses and, of course, you're delving effervescent cocktails found new journeys in cosmopolitan Istanbul.", slug: "divan", picture: "Book-a-table-at-divan.png", user_id: 2},
  {name: "Fumetto", description: "For those seeking an oriental culinary experiences, welcome to the Divan, bazaar for the senses! Here, the food is never just food! Turkish cuisine has ancient roots, Ottoman and Oriental accents that will conquer. Because Divan is where people gather to meet, to tell, to share their experiences and their plate, food different from yours. It is a magical place in the heart of Bucharest, the actual spirit dwells alike, noisy and bustling modern Turkey and traditional blast, full of stories and wisdom of the Turks of yore. Because Divan is the result of progress that respects and preserves the sanctity roots. So our dear mesean, urge you to enjoy traditional Turkish dishes, and dancing nightly to watch the show inviting the Ottoman our princesses and, of course, you're delving effervescent cocktails found new journeys in cosmopolitan Istanbul.", slug: "fumetto", picture: "Book-a-table-at-divan.png", user_id: 2}
])
# Cuisine.create!([
#  {name: "Romanian"},
#  {name: "Italian"}
# ])
